### ISSUE TITLE
Vigor seems to drain faster than normal (one tick every 6-7 seconds).

### ISSUE THREAD

**Issue by skittles1** [Daenks/Meridian59_103#884]
Haven't tracked down exactly what we did to cause this. It looks to drain at about twice the rate of 101/102.

**Comment by M59Gar** [comment]
I remember researching this quite a bit ago. I was convinced it was too fast, as were others, but then it seemed to be the same rate upon real-time testing. I'm still convinced it's too fast. It just feels wrong compared to the last 13-14 years.

Best I can guess is that it's because of the change to GetTickCount() from GetTime(). Looking at user.kod, and remembering my local server borking when this got changed, that might be it.

**Comment by cyberjunk** [comment]
>> Best I can guess is that it's because of the change to GetTickCount() from GetTime()

This was part of the higher movement/update rate.
Most vigor should be drain in UserMove() in user.kod once per second (if moving).

Our UserMove() in user.kod: 

>> %
     % 6. Drain vigor once per 1000 ms.
     %
      if iDeltaVigor >= 1000

You could try add some debug lines there and see if the vigor drain if is correctly executed once per second. The UserMove() function itself should run each ~250ms for a moving client, so only 1/4 of all executions should be stepping into the if.

Here is a link to the vanilla user.kod:
https://github.com/Meridian59/Meridian59/blob/master/kod/object/active/holder/nomoveon/battler/player/user.kod

>> % Only drain vigor once per second, unless the moves counter indicates
% we could be speedhacking.
if piLastMoveUpdateTime <> iCurrentTime
AND piMovesCounter < 0

And about:

>> I don't actually know where GetTickCount is

It is defined in ccode.c and returns a millisecond "timestamp" (GetTime returns a second timestamp).

**Comment by skittles1** [comment]
Fixed #889
